# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_build_context_synchronously: ignore

linter:
  # The lint rules applied to this project can be customized in this
  # section. For rules and documentation, see: https://dart.dev/lints
  rules:
    # Buraya istersen ek lint kuralları ekleyebilirsin.
    # örn:
    # prefer_const_constructors: true
